// Generated crate for crm/automation
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/crm/automation/openapi.yaml

// Placeholder - will be replaced during code generation
