// Generated crate for accounting/bank-sync
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/accounting/bank-sync/openapi.yaml

// Placeholder - will be replaced during code generation
