// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct Account {
    pub account_type: String,

    pub chart_of_account_id: String,

    pub code: String,

    pub created_at: String,

    pub currency_code: String,

    pub description: String,

    pub id: String,

    pub is_active: bool,

    pub is_system_account: bool,

    pub metadata: serde_json::Value,

    pub name: String,

    pub normal_balance: String,

    pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ChartOfAccount {
    pub account_type: String,

    pub code: String,

    pub created_at: String,

    pub description: String,

    pub id: String,

    pub is_active: bool,

    pub level: i32,

    pub name: String,

    pub parent_id: String,

    pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateAccountRequest {
    pub account_type: String,

    pub chart_of_account_id: String,

    pub code: String,

    pub currency_code: String,

    pub description: String,

    pub is_active: bool,

    pub name: String,

    pub normal_balance: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateAccountResponse {
    pub account_type: String,

    pub chart_of_account_id: String,

    pub code: String,

    pub created_at: String,

    pub currency_code: String,

    pub description: String,

    pub id: String,

    pub is_active: bool,

    pub is_system_account: bool,

    pub metadata: serde_json::Value,

    pub name: String,

    pub normal_balance: String,

    pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateChartOfAccountRequest {
    pub account_type: String,

    pub code: String,

    pub description: String,

    pub is_active: bool,

    pub name: String,

    pub parent_id: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateChartOfAccountResponse {
    pub account_type: String,

    pub code: String,

    pub created_at: String,

    pub description: String,

    pub id: String,

    pub is_active: bool,

    pub level: i32,

    pub name: String,

    pub parent_id: String,

    pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateJournalEntryRequest {
    pub company_id: String,

    pub currency_code: String,

    pub description: String,

    pub entry_date: String,

    pub entry_number: String,

    pub exchange_rate: f64,

    pub fiscal_period_id: String,

    pub reference_number: String,

    pub source_id: String,

    pub source_type: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateJournalEntryResponse {
    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub description: String,

    pub entry_date: String,

    pub entry_number: String,

    pub exchange_rate: f64,

    pub fiscal_period_id: String,

    pub id: String,

    pub metadata: serde_json::Value,

    pub posted_at: String,

    pub posted_by: String,

    pub reference_number: String,

    pub source_id: String,

    pub source_type: String,

    pub status: String,

    pub total_credit: f64,

    pub total_debit: f64,

    pub updated_at: String,

    pub updated_by: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetAccountResponse {
    pub account_type: String,

    pub chart_of_account_id: String,

    pub code: String,

    pub created_at: String,

    pub currency_code: String,

    pub description: String,

    pub id: String,

    pub is_active: bool,

    pub is_system_account: bool,

    pub metadata: serde_json::Value,

    pub name: String,

    pub normal_balance: String,

    pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetChartOfAccountResponse {
    pub account_type: String,

    pub code: String,

    pub created_at: String,

    pub description: String,

    pub id: String,

    pub is_active: bool,

    pub level: i32,

    pub name: String,

    pub parent_id: String,

    pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetJournalEntryResponse {
    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub description: String,

    pub entry_date: String,

    pub entry_number: String,

    pub exchange_rate: f64,

    pub fiscal_period_id: String,

    pub id: String,

    pub metadata: serde_json::Value,

    pub posted_at: String,

    pub posted_by: String,

    pub reference_number: String,

    pub source_id: String,

    pub source_type: String,

    pub status: String,

    pub total_credit: f64,

    pub total_debit: f64,

    pub updated_at: String,

    pub updated_by: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct JournalEntry {
    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub description: String,

    pub entry_date: String,

    pub entry_number: String,

    pub exchange_rate: f64,

    pub fiscal_period_id: String,

    pub id: String,

    pub metadata: serde_json::Value,

    pub posted_at: String,

    pub posted_by: String,

    pub reference_number: String,

    pub source_id: String,

    pub source_type: String,

    pub status: String,

    pub total_credit: f64,

    pub total_debit: f64,

    pub updated_at: String,

    pub updated_by: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ListAccountsResponse {
    pub items: Vec<Account>,

    pub limit: i32,

    pub page: i32,

    pub total: i32,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ListChartOfAccountsResponse {
    pub items: Vec<ChartOfAccount>,

    pub limit: i32,

    pub page: i32,

    pub total: i32,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ListJournalEntrysResponse {
    pub items: Vec<JournalEntry>,

    pub limit: i32,

    pub page: i32,

    pub total: i32,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateAccountRequest {
    pub account_type: String,

    pub description: String,

    pub is_active: bool,

    pub name: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateAccountResponse {
    pub account_type: String,

    pub chart_of_account_id: String,

    pub code: String,

    pub created_at: String,

    pub currency_code: String,

    pub description: String,

    pub id: String,

    pub is_active: bool,

    pub is_system_account: bool,

    pub metadata: serde_json::Value,

    pub name: String,

    pub normal_balance: String,

    pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateChartOfAccountRequest {
    pub account_type: String,

    pub description: String,

    pub is_active: bool,

    pub name: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateChartOfAccountResponse {
    pub account_type: String,

    pub code: String,

    pub created_at: String,

    pub description: String,

    pub id: String,

    pub is_active: bool,

    pub level: i32,

    pub name: String,

    pub parent_id: String,

    pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateJournalEntryRequest {
    pub description: String,

    pub posted_at: String,

    pub reference_number: String,

    pub status: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateJournalEntryResponse {
    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub description: String,

    pub entry_date: String,

    pub entry_number: String,

    pub exchange_rate: f64,

    pub fiscal_period_id: String,

    pub id: String,

    pub metadata: serde_json::Value,

    pub posted_at: String,

    pub posted_by: String,

    pub reference_number: String,

    pub source_id: String,

    pub source_type: String,

    pub status: String,

    pub total_credit: f64,

    pub total_debit: f64,

    pub updated_at: String,

    pub updated_by: String,
}
