// Generated crate for accounting/invoice
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/accounting/invoice/openapi.yaml

// Placeholder - will be replaced during code generation
