// Generated crate for hr/core
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/hr/core/openapi.yaml

// Placeholder - will be replaced during code generation
