// Generated crate for marketplace/integration-hub
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/marketplace/integration-hub/openapi.yaml

// Placeholder - will be replaced during code generation
