// Generated crate for hr/recruitment
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/hr/recruitment/openapi.yaml

// Placeholder - will be replaced during code generation
