// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file
use brrtrouter::dispatcher::Dispatcher;
use brrtrouter::spec::RouteMeta;
use brrtrouter::typed::spawn_typed_with_stack_size_and_name;
// Note: avoid wildcard imports to reduce warnings

/// # Safety
/// This function spawns handler coroutines. Callers must ensure coroutine runtime is set up.
#[allow(dead_code)]
pub unsafe fn register_all(dispatcher: &mut Dispatcher) {
    dispatcher.register_typed_with_stack_size(
        "list_invoice_lines",
        crate::controllers::list_invoice_lines::ListInvoiceLinesController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "create_invoice_line",
        crate::controllers::create_invoice_line::CreateInvoiceLineController,
        16384,
    );
    dispatcher.register_typed_with_stack_size(
        "get_invoice_line",
        crate::controllers::get_invoice_line::GetInvoiceLineController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "update_invoice_line",
        crate::controllers::update_invoice_line::UpdateInvoiceLineController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "delete_invoice_line",
        crate::controllers::delete_invoice_line::DeleteInvoiceLineController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "list_invoices",
        crate::controllers::list_invoices::ListInvoicesController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "create_invoice",
        crate::controllers::create_invoice::CreateInvoiceController,
        16384,
    );
    dispatcher.register_typed_with_stack_size(
        "get_invoice",
        crate::controllers::get_invoice::GetInvoiceController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "update_invoice",
        crate::controllers::update_invoice::UpdateInvoiceController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "delete_invoice",
        crate::controllers::delete_invoice::DeleteInvoiceController,
        20480,
    );
}

/// Dynamically register handlers for the provided routes using their handler names.
/// # Safety
/// This function spawns handler coroutines. Callers must ensure coroutine runtime is set up.
///
/// **IMPORTANT**: This function will clear ALL existing handlers before registering new ones
/// to prevent memory leaks from accumulating coroutines.
pub unsafe fn register_from_spec(dispatcher: &mut Dispatcher, routes: &[RouteMeta]) {
    // Clear all existing handlers to prevent memory leaks
    // The old senders will be dropped, causing their coroutines to exit
    dispatcher.handlers.clear();

    // Also clear worker pools to prevent resource leaks from previous pool-based registrations
    dispatcher.worker_pools.clear();

    for route in routes {
        // JSF P0-2: Use as_ref() for Arc<str> -> &str conversion
        match route.handler_name.as_ref() {
            "list_invoice_lines" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::list_invoice_lines::ListInvoiceLinesController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "create_invoice_line" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::create_invoice_line::CreateInvoiceLineController,
                    16384,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "get_invoice_line" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::get_invoice_line::GetInvoiceLineController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "update_invoice_line" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::update_invoice_line::UpdateInvoiceLineController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "delete_invoice_line" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::delete_invoice_line::DeleteInvoiceLineController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "list_invoices" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::list_invoices::ListInvoicesController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "create_invoice" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::create_invoice::CreateInvoiceController,
                    16384,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "get_invoice" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::get_invoice::GetInvoiceController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "update_invoice" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::update_invoice::UpdateInvoiceController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "delete_invoice" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::delete_invoice::DeleteInvoiceController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }

            _ => {}
        }
    }
}
