// Generated crate for appointments/core
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/appointments/core/openapi.yaml

// Placeholder - will be replaced during code generation
