// Generated crate for analytics/bi
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/analytics/bi/openapi.yaml

// Placeholder - will be replaced during code generation
