apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rerp
resources:
  - pipeline.yaml
  - referencegrant.yaml
configMapGenerator:
  - name: rerp-crm-common-helm-values
    files:
      - values.yaml=values/common.yaml
generatorOptions:
  disableNameSuffixHash: true
  immutable: false
