// Generated crate for ai/core
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/ai/core/openapi.yaml

// Placeholder - will be replaced during code generation
