// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file
use brrtrouter::dispatcher::HandlerRequest;
use brrtrouter::typed::TypedHandlerRequest;
use serde::{Deserialize, Serialize};
use std::convert::TryFrom;

#[derive(Debug, Deserialize, Serialize)]
pub struct Request {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "notes")]
    pub notes: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "payment_amount")]
    pub payment_amount: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "payment_date")]
    pub payment_date: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "payment_method")]
    pub payment_method: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "status")]
    pub status: Option<String>,

    #[serde(rename = "id")]
    pub id: String,
}

#[derive(Debug, Serialize)]

pub struct Response {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "applied_amount")]
    pub applied_amount: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "bank_account_id")]
    pub bank_account_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "company_id")]
    pub company_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "created_at")]
    pub created_at: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "created_by")]
    pub created_by: Option<String>,

    #[serde(rename = "currency_code")]
    pub currency_code: String,

    #[serde(rename = "id")]
    pub id: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "metadata")]
    pub metadata: Option<serde_json::Value>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "notes")]
    pub notes: Option<String>,

    #[serde(rename = "payment_amount")]
    pub payment_amount: f64,

    #[serde(rename = "payment_date")]
    pub payment_date: String,

    #[serde(rename = "payment_method")]
    pub payment_method: String,

    #[serde(rename = "payment_number")]
    pub payment_number: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "payment_reference")]
    pub payment_reference: Option<String>,

    #[serde(rename = "status")]
    pub status: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "updated_at")]
    pub updated_at: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "updated_by")]
    pub updated_by: Option<String>,

    #[serde(rename = "vendor_id")]
    pub vendor_id: String,
}

impl TryFrom<HandlerRequest> for Request {
    type Error = anyhow::Error;

    fn try_from(req: HandlerRequest) -> Result<Self, Self::Error> {
        use serde_json::{Map, Value};

        let mut data_map = Map::new();

        if let Some(v) = req.get_path_param("id") {
            data_map.insert(
                "id".to_string(),
                brrtrouter::server::request::decode_param_value(
                    v,
                    Some(&serde_json::json!({"format":"uuid","type":"string"})),
                    None,
                    None,
                ),
            );
        } else {
            return Err(anyhow::anyhow!("Missing required parameter 'id'"));
        }

        if let Some(body) = req.body {
            match body {
                Value::Object(map) => {
                    for (k, v) in map {
                        data_map.insert(k, v);
                    }
                }
                other => {
                    data_map.insert("body".to_string(), other);
                }
            }
        }

        Ok(serde_json::from_value(Value::Object(data_map))?)
    }
}

#[allow(dead_code)]
pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    crate::controllers::update_payment::handle(req)
}
