// Generated crate for pos/payment-gateway
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/pos/payment-gateway/openapi.yaml

// Placeholder - will be replaced during code generation
