// Generated crate for data/cleaning
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/data/cleaning/openapi.yaml

// Placeholder - will be replaced during code generation
