// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file

pub mod types;

pub mod list_financial_statements;

pub mod create_financial_statement;

pub mod get_financial_statement;

pub mod update_financial_statement;

pub mod delete_financial_statement;

pub mod list_reports;

pub mod create_report;

pub mod get_report;

pub mod update_report;

pub mod delete_report;
