// Generated crate for website/cms
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/website/cms/openapi.yaml

// Placeholder - will be replaced during code generation
