// Auto-generated mod.rs for bank-sync entities
// DO NOT EDIT - this is generated by the build system

pub mod bank;
pub mod bank_account;
pub mod bank_reconciliation;
pub mod bank_statement;
pub mod bank_transaction;

pub mod entity_registry {
    include!(concat!(env!("OUT_DIR"), "/entity_registry.rs"));
}
