// Generated crate for inventory/warehouse
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/inventory/warehouse/openapi.yaml

// Placeholder - will be replaced during code generation
