// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file

pub mod list_accounts;

pub mod create_account;

pub mod get_account;

pub mod update_account;

pub mod delete_account;

pub mod list_chart_of_accounts;

pub mod create_chart_of_account;

pub mod get_chart_of_account;

pub mod update_chart_of_account;

pub mod delete_chart_of_account;

pub mod create_journal_entry;

pub mod get_journal_entry;

pub mod update_journal_entry;

pub mod account_balances_report;
pub mod approve_journal_entry;
pub mod bulk_approve_journal_entries;
pub mod bulk_post_journal_entries;
pub mod close_fiscal_year;
pub mod create_chart_template;
pub mod create_currency_revaluation;
pub mod create_fiscal_period;
pub mod create_fiscal_position;
pub mod create_fiscal_year;
pub mod create_journal;
pub mod create_lock_date;
pub mod create_payment_method;
pub mod create_payment_term;
pub mod create_tax_repartition_line;
pub mod delete_chart_template;
pub mod delete_fiscal_period;
pub mod delete_fiscal_position;
pub mod delete_fiscal_year;
pub mod delete_journal;
pub mod delete_journal_entry;
pub mod delete_payment_method;
pub mod delete_payment_term;
pub mod delete_tax_repartition_line;
pub mod deploy_chart_template;
pub mod generate_fiscal_year_periods;
pub mod get_account_balance;
pub mod get_chart_template;
pub mod get_fiscal_period;
pub mod get_fiscal_position;
pub mod get_fiscal_year;
pub mod get_journal;
pub mod get_payment_method;
pub mod get_payment_term;
pub mod get_tax_repartition_line;
pub mod ledger_report;
pub mod list_chart_templates;
pub mod list_fiscal_periods;
pub mod list_fiscal_positions;
pub mod list_fiscal_year_periods;
pub mod list_fiscal_years;
pub mod list_journal_entries;
pub mod list_journal_entries_by_journal;
pub mod list_journal_entry_lines;
pub mod list_journal_items;
pub mod list_journals;
pub mod list_lock_dates;
pub mod list_payment_method_journal_mappings;
pub mod list_payment_methods;
pub mod list_payment_terms;
pub mod list_tax_repartition_lines;
pub mod post_journal_entry;
pub mod reconcile_journal_items;
pub mod reopen_fiscal_year;
pub mod reverse_journal_entry;
pub mod trial_balance;
pub mod unreconcile_journal_items;
pub mod update_chart_template;
pub mod update_fiscal_period;
pub mod update_fiscal_position;
pub mod update_fiscal_year;
pub mod update_journal;
pub mod update_payment_method;
pub mod update_payment_term;
pub mod update_tax_repartition_line;
