// Generated crate for accounting/accounts-receivable
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/accounting/accounts-receivable/openapi.yaml

// Placeholder - will be replaced during code generation
