// Generated crate for project/timesheet
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/project/timesheet/openapi.yaml

// Placeholder - will be replaced during code generation
