// Generated crate for manufacturing/bom
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/manufacturing/bom/openapi.yaml

// Placeholder - will be replaced during code generation
