// Generated crate for inventory/core
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/inventory/core/openapi.yaml

// Placeholder - will be replaced during code generation
