// Generated crate for sales/quotation
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/sales/quotation/openapi.yaml

// Placeholder - will be replaced during code generation
