// Generated crate for crm/core
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/crm/core/openapi.yaml

// Placeholder - will be replaced during code generation
