// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation

pub mod credit_customer_invoice;
pub mod get_customer_invoice;
pub mod get_customer_invoice_document;
pub mod get_customer_invoice_journal;
pub mod post_customer_invoice;
