// Generated crate for approvals/core
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/approvals/core/openapi.yaml

// Placeholder - will be replaced during code generation
