// Generated crate for accounting/accounts-payable
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/accounting/accounts-payable/openapi.yaml

// Placeholder - will be replaced during code generation
