// Generated crate for marketing/email
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/marketing/email/openapi.yaml

// Placeholder - will be replaced during code generation
