// Auto-generated mod.rs for invoice entities
// DO NOT EDIT - this is generated by the build system

pub mod invoice;
pub mod invoice_line;

pub mod entity_registry {
    include!(concat!(env!("OUT_DIR"), "/entity_registry.rs"));
}
