// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file

pub mod types;

pub mod list_ar_agings;

pub mod create_ar_aging;

pub mod get_ar_aging;

pub mod update_ar_aging;

pub mod delete_ar_aging;

pub mod list_customer_invoices;

pub mod create_customer_invoice;

pub mod get_customer_invoice;

pub mod update_customer_invoice;

pub mod delete_customer_invoice;

pub mod list_payments;

pub mod create_payment;

pub mod get_payment;

pub mod update_payment;

pub mod delete_payment;
