// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ArAging {
    pub aging_date: String,

    pub company_id: String,

    pub created_at: String,

    pub currency_code: String,

    pub current: f64,

    pub customer_id: String,

    pub days_31_60: f64,

    pub days_61_90: f64,

    pub days_91_120: f64,

    pub id: String,

    pub over_120: f64,

    pub total_outstanding: f64,

    pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateArAgingRequest {
    pub aging_date: String,

    pub company_id: String,

    pub currency_code: String,

    pub customer_id: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateArAgingResponse {
    pub aging_date: String,

    pub company_id: String,

    pub created_at: String,

    pub currency_code: String,

    pub current: f64,

    pub customer_id: String,

    pub days_31_60: f64,

    pub days_61_90: f64,

    pub days_91_120: f64,

    pub id: String,

    pub over_120: f64,

    pub total_outstanding: f64,

    pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateCustomerInvoiceRequest {
    pub collection_status: String,

    pub credit_limit: f64,

    pub customer_id: String,

    pub invoice_id: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateCustomerInvoiceResponse {
    pub aging_bucket: String,

    pub collection_status: String,

    pub created_at: String,

    pub credit_limit: f64,

    pub credit_used: f64,

    pub customer_id: String,

    pub days_overdue: i32,

    pub id: String,

    pub invoice_id: String,

    pub last_payment_amount: f64,

    pub last_payment_date: String,

    pub metadata: serde_json::Value,

    pub outstanding_amount: f64,

    pub updated_at: String,

    pub write_off_amount: f64,

    pub write_off_date: String,

    pub write_off_reason: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreatePaymentApplicationRequest {
    pub applied_amount: f64,

    pub invoice_id: String,

    pub notes: String,

    pub payment_id: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreatePaymentRequest {
    pub bank_account_id: String,

    pub company_id: String,

    pub currency_code: String,

    pub customer_id: String,

    pub exchange_rate: f64,

    pub notes: String,

    pub payment_amount: f64,

    pub payment_date: String,

    pub payment_method: String,

    pub payment_number: String,

    pub payment_reference: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreatePaymentResponse {
    pub applied_amount: f64,

    pub bank_account_id: String,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub customer_id: String,

    pub exchange_rate: f64,

    pub id: String,

    pub metadata: serde_json::Value,

    pub notes: String,

    pub payment_amount: f64,

    pub payment_date: String,

    pub payment_method: String,

    pub payment_number: String,

    pub payment_reference: String,

    pub reconciled_at: String,

    pub reconciled_by: String,

    pub status: String,

    pub unapplied_amount: f64,

    pub updated_at: String,

    pub updated_by: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CustomerInvoice {
    pub aging_bucket: String,

    pub collection_status: String,

    pub created_at: String,

    pub credit_limit: f64,

    pub credit_used: f64,

    pub customer_id: String,

    pub days_overdue: i32,

    pub id: String,

    pub invoice_id: String,

    pub last_payment_amount: f64,

    pub last_payment_date: String,

    pub metadata: serde_json::Value,

    pub outstanding_amount: f64,

    pub updated_at: String,

    pub write_off_amount: f64,

    pub write_off_date: String,

    pub write_off_reason: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetArAgingResponse {
    pub aging_date: String,

    pub company_id: String,

    pub created_at: String,

    pub currency_code: String,

    pub current: f64,

    pub customer_id: String,

    pub days_31_60: f64,

    pub days_61_90: f64,

    pub days_91_120: f64,

    pub id: String,

    pub over_120: f64,

    pub total_outstanding: f64,

    pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetCustomerInvoiceResponse {
    pub aging_bucket: String,

    pub collection_status: String,

    pub created_at: String,

    pub credit_limit: f64,

    pub credit_used: f64,

    pub customer_id: String,

    pub days_overdue: i32,

    pub id: String,

    pub invoice_id: String,

    pub last_payment_amount: f64,

    pub last_payment_date: String,

    pub metadata: serde_json::Value,

    pub outstanding_amount: f64,

    pub updated_at: String,

    pub write_off_amount: f64,

    pub write_off_date: String,

    pub write_off_reason: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetPaymentResponse {
    pub applied_amount: f64,

    pub bank_account_id: String,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub customer_id: String,

    pub exchange_rate: f64,

    pub id: String,

    pub metadata: serde_json::Value,

    pub notes: String,

    pub payment_amount: f64,

    pub payment_date: String,

    pub payment_method: String,

    pub payment_number: String,

    pub payment_reference: String,

    pub reconciled_at: String,

    pub reconciled_by: String,

    pub status: String,

    pub unapplied_amount: f64,

    pub updated_at: String,

    pub updated_by: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ListArAgingsResponse {
    pub items: Vec<ArAging>,

    pub limit: i32,

    pub page: i32,

    pub total: i32,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ListCustomerInvoicesResponse {
    pub items: Vec<CustomerInvoice>,

    pub limit: i32,

    pub page: i32,

    pub total: i32,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ListPaymentsResponse {
    pub items: Vec<Payment>,

    pub limit: i32,

    pub page: i32,

    pub total: i32,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct Payment {
    pub applied_amount: f64,

    pub bank_account_id: String,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub customer_id: String,

    pub exchange_rate: f64,

    pub id: String,

    pub metadata: serde_json::Value,

    pub notes: String,

    pub payment_amount: f64,

    pub payment_date: String,

    pub payment_method: String,

    pub payment_number: String,

    pub payment_reference: String,

    pub reconciled_at: String,

    pub reconciled_by: String,

    pub status: String,

    pub unapplied_amount: f64,

    pub updated_at: String,

    pub updated_by: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct PaymentApplication {
    pub applied_amount: f64,

    pub applied_at: String,

    pub applied_by: String,

    pub created_at: String,

    pub id: String,

    pub invoice_id: String,

    pub notes: String,

    pub payment_id: String,

    pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateArAgingRequest {
    pub current: f64,

    pub days_31_60: f64,

    pub days_61_90: f64,

    pub days_91_120: f64,

    pub over_120: f64,

    pub total_outstanding: f64,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateArAgingResponse {
    pub aging_date: String,

    pub company_id: String,

    pub created_at: String,

    pub currency_code: String,

    pub current: f64,

    pub customer_id: String,

    pub days_31_60: f64,

    pub days_61_90: f64,

    pub days_91_120: f64,

    pub id: String,

    pub over_120: f64,

    pub total_outstanding: f64,

    pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateCustomerInvoiceRequest {
    pub aging_bucket: String,

    pub collection_status: String,

    pub outstanding_amount: f64,

    pub write_off_amount: f64,

    pub write_off_date: String,

    pub write_off_reason: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateCustomerInvoiceResponse {
    pub aging_bucket: String,

    pub collection_status: String,

    pub created_at: String,

    pub credit_limit: f64,

    pub credit_used: f64,

    pub customer_id: String,

    pub days_overdue: i32,

    pub id: String,

    pub invoice_id: String,

    pub last_payment_amount: f64,

    pub last_payment_date: String,

    pub metadata: serde_json::Value,

    pub outstanding_amount: f64,

    pub updated_at: String,

    pub write_off_amount: f64,

    pub write_off_date: String,

    pub write_off_reason: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdatePaymentApplicationRequest {
    pub applied_amount: f64,

    pub notes: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdatePaymentRequest {
    pub notes: String,

    pub payment_amount: f64,

    pub payment_date: String,

    pub payment_method: String,

    pub status: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdatePaymentResponse {
    pub applied_amount: f64,

    pub bank_account_id: String,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub customer_id: String,

    pub exchange_rate: f64,

    pub id: String,

    pub metadata: serde_json::Value,

    pub notes: String,

    pub payment_amount: f64,

    pub payment_date: String,

    pub payment_method: String,

    pub payment_number: String,

    pub payment_reference: String,

    pub reconciled_at: String,

    pub reconciled_by: String,

    pub status: String,

    pub unapplied_amount: f64,

    pub updated_at: String,

    pub updated_by: String,
}
