// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file
use brrtrouter::dispatcher::HandlerRequest;
use brrtrouter::typed::TypedHandlerRequest;
use serde::{Deserialize, Serialize};
use std::convert::TryFrom;

#[derive(Debug, Deserialize, Serialize)]
pub struct Request {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "current")]
    pub current: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "days_31_60")]
    pub days_31_60: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "days_61_90")]
    pub days_61_90: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "days_91_120")]
    pub days_91_120: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "over_120")]
    pub over_120: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "total_outstanding")]
    pub total_outstanding: Option<f64>,

    #[serde(rename = "id")]
    pub id: String,
}

#[derive(Debug, Serialize)]

pub struct Response {
    #[serde(rename = "aging_date")]
    pub aging_date: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "company_id")]
    pub company_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "created_at")]
    pub created_at: Option<String>,

    #[serde(rename = "currency_code")]
    pub currency_code: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "current")]
    pub current: Option<f64>,

    #[serde(rename = "customer_id")]
    pub customer_id: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "days_31_60")]
    pub days_31_60: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "days_61_90")]
    pub days_61_90: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "days_91_120")]
    pub days_91_120: Option<f64>,

    #[serde(rename = "id")]
    pub id: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "over_120")]
    pub over_120: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "total_outstanding")]
    pub total_outstanding: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "updated_at")]
    pub updated_at: Option<String>,
}

impl TryFrom<HandlerRequest> for Request {
    type Error = anyhow::Error;

    fn try_from(req: HandlerRequest) -> Result<Self, Self::Error> {
        use serde_json::{Map, Value};

        let mut data_map = Map::new();

        if let Some(v) = req.get_path_param("id") {
            data_map.insert(
                "id".to_string(),
                brrtrouter::server::request::decode_param_value(
                    v,
                    Some(&serde_json::json!({"format":"uuid","type":"string"})),
                    None,
                    None,
                ),
            );
        } else {
            return Err(anyhow::anyhow!("Missing required parameter 'id'"));
        }

        if let Some(body) = req.body {
            match body {
                Value::Object(map) => {
                    for (k, v) in map {
                        data_map.insert(k, v);
                    }
                }
                other => {
                    data_map.insert("body".to_string(), other);
                }
            }
        }

        Ok(serde_json::from_value(Value::Object(data_map))?)
    }
}

#[allow(dead_code)]
pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    crate::controllers::update_ar_aging::handle(req)
}
