// Auto-generated mod.rs for accounts-receivable entities
// DO NOT EDIT - this is generated by the build system

pub mod ar_aging;
pub mod ar_payment;
pub mod ar_payment_application;
pub mod customer_invoice;

pub mod entity_registry {
    include!(concat!(env!("OUT_DIR"), "/entity_registry.rs"));
}
