// Auto-generated mod.rs for edi entities
// DO NOT EDIT - this is generated by the build system

pub mod edi_acknowledgment;
pub mod edi_document;
pub mod edi_format;
pub mod edi_mapping;

pub mod entity_registry {
    include!(concat!(env!("OUT_DIR"), "/entity_registry.rs"));
}

