// ⚠️ WARNING: This file is auto-generated by BRRTRouter for the **impl** crate
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next `brrtrouter-gen generate-stubs`
// ⚠️ Business logic belongs in impl/src/controllers/<operationId>.rs (user-owned)
//
// ADR 0001 Layer 2: `register_impl` overrides gen mock handlers for controllers
// discovered on disk. The gen crate's `registry.rs` (`register_from_spec`) runs first;
// this module replaces matching routes with impl controllers.
//
// NOT the same as:
//   - gen/src/registry.rs        (template: registry.rs.txt — mock layer)
//   - cylon-skills registry.rs   (unrelated skills/personalities JSON index)

use brrtrouter::dispatcher::Dispatcher;
use brrtrouter::spec::RouteMeta;
use brrtrouter::typed::spawn_typed_with_stack_size_and_name;

/// Register impl controllers discovered on disk (overrides gen stubs per ADR 0001 Layer 2).
///
/// # Safety
/// Spawns handler coroutines. Callers must ensure the coroutine runtime is initialized.
pub unsafe fn register_impl(dispatcher: &mut Dispatcher, routes: &[RouteMeta]) {
    for route in routes {
        match route.handler_name.as_ref() {
            "create_document_rendition" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::create_document_rendition::CreateDocumentRenditionController,
                    16384,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "create_document_rendition_copy" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::create_document_rendition_copy::CreateDocumentRenditionCopyController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "create_document_rendition_download" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::create_document_rendition_download::CreateDocumentRenditionDownloadController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "create_document_template" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::create_document_template::CreateDocumentTemplateController,
                    16384,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "create_document_template_version" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::create_document_template_version::CreateDocumentTemplateVersionController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "get_document_rendition" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::get_document_rendition::GetDocumentRenditionController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "get_document_template" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::get_document_template::GetDocumentTemplateController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "get_document_template_version" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::get_document_template_version::GetDocumentTemplateVersionController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "list_document_template_versions" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::list_document_template_versions::ListDocumentTemplateVersionsController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "list_document_templates" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::list_document_templates::ListDocumentTemplatesController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "list_source_document_renditions" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::list_source_document_renditions::ListSourceDocumentRenditionsController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "preview_document_template_version" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::preview_document_template_version::PreviewDocumentTemplateVersionController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "publish_document_template_version" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::publish_document_template_version::PublishDocumentTemplateVersionController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "retire_document_template_version" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::retire_document_template_version::RetireDocumentTemplateVersionController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "validate_document_template_version" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::validate_document_template_version::ValidateDocumentTemplateVersionController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            _ => {}
        }
    }
}
