// Generated crate for hr/attendance
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/hr/attendance/openapi.yaml

// Placeholder - will be replaced during code generation
