// Generated crate for infrastructure/integration-platform
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/infrastructure/integration-platform/openapi.yaml

// Placeholder - will be replaced during code generation
