// Generated crate for marketing/automation
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/marketing/automation/openapi.yaml

// Placeholder - will be replaced during code generation
