// Generated crate for sales/loyalty
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/sales/loyalty/openapi.yaml

// Placeholder - will be replaced during code generation
