// Generated crate for localization/compliance
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/localization/compliance/openapi.yaml

// Placeholder - will be replaced during code generation
