// Generated crate for helpdesk/core
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/helpdesk/core/openapi.yaml

// Placeholder - will be replaced during code generation
