// Generated crate for accounting/general-ledger
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/accounting/general-ledger/openapi.yaml

// Placeholder - will be replaced during code generation
