// Generated crate for iot/core
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/iot/core/openapi.yaml

// Placeholder - will be replaced during code generation
