// Generated crate for inventory/dropshipping
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/inventory/dropshipping/openapi.yaml

// Placeholder - will be replaced during code generation
