// Generated crate for product/tax
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/product/tax/openapi.yaml

// Placeholder - will be replaced during code generation
