// Auto-generated mod.rs for budget entities
// DO NOT EDIT - this is generated by the build system

pub mod budget;
pub mod budget_actual;
pub mod budget_line_item;
pub mod budget_period;
pub mod budget_version;

pub mod entity_registry {
    include!(concat!(env!("OUT_DIR"), "/entity_registry.rs"));
}
