// Generated crate for marketplace/core
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/marketplace/core/openapi.yaml

// Placeholder - will be replaced during code generation
