// Generated crate for product/catalog
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/product/catalog/openapi.yaml

// Placeholder - will be replaced during code generation
