// Generated crate for purchase/core
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/purchase/core/openapi.yaml

// Placeholder - will be replaced during code generation
