// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file

pub mod list_asset_registers;

pub mod create_asset_register;

pub mod get_asset_register;

pub mod update_asset_register;

pub mod delete_asset_register;

pub mod list_assets;

pub mod create_asset;

pub mod get_asset;

pub mod update_asset;

pub mod delete_asset;

pub mod list_depreciations;

pub mod create_depreciation;

pub mod get_depreciation;

pub mod update_depreciation;

pub mod delete_depreciation;
