// Generated crate for manufacturing/production-planning
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/manufacturing/production-planning/openapi.yaml

// Placeholder - will be replaced during code generation
