// Generated crate for project/core
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/project/core/openapi.yaml

// Placeholder - will be replaced during code generation
