// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file
use brrtrouter::dispatcher::HandlerRequest;
use brrtrouter::typed::TypedHandlerRequest;
use serde::{Deserialize, Serialize};
use std::convert::TryFrom;

#[derive(Debug, Deserialize, Serialize)]
pub struct Request {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "description")]
    pub description: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "disposal_date")]
    pub disposal_date: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "location")]
    pub location: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "name")]
    pub name: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "status")]
    pub status: Option<String>,

    #[serde(rename = "id")]
    pub id: String,
}

#[derive(Debug, Serialize)]

pub struct Response {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "accumulated_depreciation")]
    pub accumulated_depreciation: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "accumulated_depreciation_account_id")]
    pub accumulated_depreciation_account_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "asset_account_id")]
    pub asset_account_id: Option<String>,

    #[serde(rename = "asset_number")]
    pub asset_number: String,

    #[serde(rename = "category_id")]
    pub category_id: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "company_id")]
    pub company_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "created_at")]
    pub created_at: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "created_by")]
    pub created_by: Option<String>,

    #[serde(rename = "currency_code")]
    pub currency_code: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "current_value")]
    pub current_value: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "depreciation_expense_account_id")]
    pub depreciation_expense_account_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "depreciation_method")]
    pub depreciation_method: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "depreciation_rate")]
    pub depreciation_rate: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "description")]
    pub description: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "disposal_date")]
    pub disposal_date: Option<String>,

    #[serde(rename = "id")]
    pub id: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "in_service_date")]
    pub in_service_date: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "location")]
    pub location: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "metadata")]
    pub metadata: Option<serde_json::Value>,

    #[serde(rename = "name")]
    pub name: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "purchase_cost")]
    pub purchase_cost: Option<f64>,

    #[serde(rename = "purchase_date")]
    pub purchase_date: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "salvage_value")]
    pub salvage_value: Option<f64>,

    #[serde(rename = "status")]
    pub status: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "updated_at")]
    pub updated_at: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "updated_by")]
    pub updated_by: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "useful_life_months")]
    pub useful_life_months: Option<i32>,
}

impl TryFrom<HandlerRequest> for Request {
    type Error = anyhow::Error;

    fn try_from(req: HandlerRequest) -> Result<Self, Self::Error> {
        use serde_json::{Map, Value};

        let mut data_map = Map::new();

        if let Some(v) = req.get_path_param("id") {
            data_map.insert(
                "id".to_string(),
                brrtrouter::server::request::decode_param_value(
                    v,
                    Some(&serde_json::json!({"format":"uuid","type":"string"})),
                    None,
                    None,
                ),
            );
        } else {
            return Err(anyhow::anyhow!("Missing required parameter 'id'"));
        }

        if let Some(body) = req.body {
            match body {
                Value::Object(map) => {
                    for (k, v) in map {
                        data_map.insert(k, v);
                    }
                }
                other => {
                    data_map.insert("body".to_string(), other);
                }
            }
        }

        Ok(serde_json::from_value(Value::Object(data_map))?)
    }
}

#[allow(dead_code)]
pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    crate::controllers::update_asset::handle(req)
}
