// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file
use brrtrouter::dispatcher::Dispatcher;
use brrtrouter::spec::RouteMeta;
use brrtrouter::typed::spawn_typed_with_stack_size_and_name;
// Note: avoid wildcard imports to reduce warnings

/// # Safety
/// This function spawns handler coroutines. Callers must ensure coroutine runtime is set up.
#[allow(dead_code)]
pub unsafe fn register_all(dispatcher: &mut Dispatcher) {
    dispatcher.register_typed_with_stack_size(
        "listAccounts",
        crate::controllers::listAccounts::ListAccountsController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "createAccount",
        crate::controllers::createAccount::CreateAccountController,
        16384,
    );
    dispatcher.register_typed_with_stack_size(
        "getAccount",
        crate::controllers::getAccount::GetAccountController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "updateAccount",
        crate::controllers::updateAccount::UpdateAccountController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "deleteAccount",
        crate::controllers::deleteAccount::DeleteAccountController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "listChartOfAccounts",
        crate::controllers::listChartOfAccounts::ListChartOfAccountsController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "createChartOfAccount",
        crate::controllers::createChartOfAccount::CreateChartOfAccountController,
        16384,
    );
    dispatcher.register_typed_with_stack_size(
        "getChartOfAccount",
        crate::controllers::getChartOfAccount::GetChartOfAccountController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "updateChartOfAccount",
        crate::controllers::updateChartOfAccount::UpdateChartOfAccountController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "deleteChartOfAccount",
        crate::controllers::deleteChartOfAccount::DeleteChartOfAccountController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "listJournalEntrys",
        crate::controllers::listJournalEntrys::ListJournalEntrysController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "createJournalEntry",
        crate::controllers::createJournalEntry::CreateJournalEntryController,
        16384,
    );
    dispatcher.register_typed_with_stack_size(
        "getJournalEntry",
        crate::controllers::getJournalEntry::GetJournalEntryController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "updateJournalEntry",
        crate::controllers::updateJournalEntry::UpdateJournalEntryController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "deleteJournalEntry",
        crate::controllers::deleteJournalEntry::DeleteJournalEntryController,
        20480,
    );
}

/// Dynamically register handlers for the provided routes using their handler names.
/// # Safety
/// This function spawns handler coroutines. Callers must ensure coroutine runtime is set up.
///
/// **IMPORTANT**: This function will clear ALL existing handlers before registering new ones
/// to prevent memory leaks from accumulating coroutines.
pub unsafe fn register_from_spec(dispatcher: &mut Dispatcher, routes: &[RouteMeta]) {
    // Clear all existing handlers to prevent memory leaks
    // The old senders will be dropped, causing their coroutines to exit
    dispatcher.handlers.clear();

    // Also clear worker pools to prevent resource leaks from previous pool-based registrations
    dispatcher.worker_pools.clear();

    for route in routes {
        // JSF P0-2: Use as_ref() for Arc<str> -> &str conversion
        match route.handler_name.as_ref() {
            "listAccounts" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::listAccounts::ListAccountsController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "createAccount" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::createAccount::CreateAccountController,
                    16384,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "getAccount" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::getAccount::GetAccountController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "updateAccount" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::updateAccount::UpdateAccountController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "deleteAccount" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::deleteAccount::DeleteAccountController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "listChartOfAccounts" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::listChartOfAccounts::ListChartOfAccountsController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "createChartOfAccount" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::createChartOfAccount::CreateChartOfAccountController,
                    16384,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "getChartOfAccount" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::getChartOfAccount::GetChartOfAccountController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "updateChartOfAccount" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::updateChartOfAccount::UpdateChartOfAccountController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "deleteChartOfAccount" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::deleteChartOfAccount::DeleteChartOfAccountController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "listJournalEntrys" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::listJournalEntrys::ListJournalEntrysController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "createJournalEntry" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::createJournalEntry::CreateJournalEntryController,
                    16384,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "getJournalEntry" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::getJournalEntry::GetJournalEntryController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "updateJournalEntry" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::updateJournalEntry::UpdateJournalEntryController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "deleteJournalEntry" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::deleteJournalEntry::DeleteJournalEntryController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }

            _ => {}
        }
    }
}
