// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file
use brrtrouter::dispatcher::Dispatcher;
use brrtrouter::spec::RouteMeta;
use brrtrouter::typed::spawn_typed_with_stack_size_and_name;
// Note: avoid wildcard imports to reduce warnings

/// # Safety
/// This function spawns handler coroutines. Callers must ensure coroutine runtime is set up.
#[allow(dead_code)]
pub unsafe fn register_all(dispatcher: &mut Dispatcher) {
    dispatcher.register_typed_with_stack_size(
        "list_accounts",
        crate::controllers::list_accounts::ListAccountsController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "create_account",
        crate::controllers::create_account::CreateAccountController,
        16384,
    );
    dispatcher.register_typed_with_stack_size(
        "get_account",
        crate::controllers::get_account::GetAccountController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "update_account",
        crate::controllers::update_account::UpdateAccountController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "delete_account",
        crate::controllers::delete_account::DeleteAccountController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "list_chart_of_accounts",
        crate::controllers::list_chart_of_accounts::ListChartOfAccountsController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "create_chart_of_account",
        crate::controllers::create_chart_of_account::CreateChartOfAccountController,
        16384,
    );
    dispatcher.register_typed_with_stack_size(
        "get_chart_of_account",
        crate::controllers::get_chart_of_account::GetChartOfAccountController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "update_chart_of_account",
        crate::controllers::update_chart_of_account::UpdateChartOfAccountController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "delete_chart_of_account",
        crate::controllers::delete_chart_of_account::DeleteChartOfAccountController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "list_journal_entrys",
        crate::controllers::list_journal_entrys::ListJournalEntrysController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "create_journal_entry",
        crate::controllers::create_journal_entry::CreateJournalEntryController,
        16384,
    );
    dispatcher.register_typed_with_stack_size(
        "get_journal_entry",
        crate::controllers::get_journal_entry::GetJournalEntryController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "update_journal_entry",
        crate::controllers::update_journal_entry::UpdateJournalEntryController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "delete_journal_entry",
        crate::controllers::delete_journal_entry::DeleteJournalEntryController,
        20480,
    );
}

/// Dynamically register handlers for the provided routes using their handler names.
/// # Safety
/// This function spawns handler coroutines. Callers must ensure coroutine runtime is set up.
///
/// **IMPORTANT**: This function will clear ALL existing handlers before registering new ones
/// to prevent memory leaks from accumulating coroutines.
pub unsafe fn register_from_spec(dispatcher: &mut Dispatcher, routes: &[RouteMeta]) {
    // Clear all existing handlers to prevent memory leaks
    // The old senders will be dropped, causing their coroutines to exit
    dispatcher.handlers.clear();

    // Also clear worker pools to prevent resource leaks from previous pool-based registrations
    dispatcher.worker_pools.clear();

    for route in routes {
        // JSF P0-2: Use as_ref() for Arc<str> -> &str conversion
        match route.handler_name.as_ref() {
            "list_accounts" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::list_accounts::ListAccountsController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "create_account" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::create_account::CreateAccountController,
                    16384,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "get_account" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::get_account::GetAccountController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "update_account" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::update_account::UpdateAccountController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "delete_account" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::delete_account::DeleteAccountController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "list_chart_of_accounts" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::list_chart_of_accounts::ListChartOfAccountsController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "create_chart_of_account" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::create_chart_of_account::CreateChartOfAccountController,
                    16384,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "get_chart_of_account" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::get_chart_of_account::GetChartOfAccountController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "update_chart_of_account" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::update_chart_of_account::UpdateChartOfAccountController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "delete_chart_of_account" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::delete_chart_of_account::DeleteChartOfAccountController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "list_journal_entrys" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::list_journal_entrys::ListJournalEntrysController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "create_journal_entry" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::create_journal_entry::CreateJournalEntryController,
                    16384,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "get_journal_entry" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::get_journal_entry::GetJournalEntryController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "update_journal_entry" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::update_journal_entry::UpdateJournalEntryController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "delete_journal_entry" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::delete_journal_entry::DeleteJournalEntryController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }

            _ => {}
        }
    }
}
