// Generated crate for analytics/reporting
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/analytics/reporting/openapi.yaml

// Placeholder - will be replaced during code generation
