// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file

pub mod types;

pub mod list_edi_documents;

pub mod create_edi_document;

pub mod get_edi_document;

pub mod update_edi_document;

pub mod delete_edi_document;

pub mod list_edi_mappings;

pub mod create_edi_mapping;

pub mod get_edi_mapping;

pub mod update_edi_mapping;

pub mod delete_edi_mapping;
