// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateEdiDocumentRequest {
    pub company_id: String,

    pub document_number: String,

    pub document_type: String,

    pub format_id: String,

    pub raw_content: String,

    pub receiver_id: String,

    pub sender_id: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateEdiDocumentResponse {
    pub acknowledgment_sent: bool,

    pub acknowledgment_sent_at: String,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub document_number: String,

    pub document_type: String,

    pub error_details: serde_json::Value,

    pub error_message: String,

    pub format_id: String,

    pub id: String,

    pub last_retry_at: String,

    pub metadata: serde_json::Value,

    pub parsed_at: String,

    pub parsed_data: serde_json::Value,

    pub processed_at: String,

    pub raw_content: String,

    pub received_at: String,

    pub receiver_id: String,

    pub related_invoice_id: String,

    pub related_purchase_order_id: String,

    pub retry_count: i32,

    pub sender_id: String,

    pub status: String,

    pub updated_at: String,

    pub updated_by: String,

    pub validated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateEdiMappingRequest {
    pub default_values: serde_json::Value,

    pub description: String,

    pub document_type: String,

    pub field_mappings: serde_json::Value,

    pub format_id: String,

    pub is_active: bool,

    pub mapping_name: String,

    pub transformation_rules: serde_json::Value,

    pub validation_rules: serde_json::Value,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateEdiMappingResponse {
    pub created_at: String,

    pub created_by: String,

    pub default_values: serde_json::Value,

    pub description: String,

    pub document_type: String,

    pub field_mappings: serde_json::Value,

    pub format_id: String,

    pub id: String,

    pub is_active: bool,

    pub mapping_name: String,

    pub transformation_rules: serde_json::Value,

    pub updated_at: String,

    pub updated_by: String,

    pub validation_rules: serde_json::Value,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct EdiAcknowledgment {
    pub acknowledgment_content: String,

    pub acknowledgment_data: serde_json::Value,

    pub acknowledgment_type: String,

    pub created_at: String,

    pub document_id: String,

    pub error_codes: serde_json::Value,

    pub error_messages: String,

    pub id: String,

    pub metadata: serde_json::Value,

    pub received_at: String,

    pub sent_at: String,

    pub status: String,

    pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct EdiDocument {
    pub acknowledgment_sent: bool,

    pub acknowledgment_sent_at: String,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub document_number: String,

    pub document_type: String,

    pub error_details: serde_json::Value,

    pub error_message: String,

    pub format_id: String,

    pub id: String,

    pub last_retry_at: String,

    pub metadata: serde_json::Value,

    pub parsed_at: String,

    pub parsed_data: serde_json::Value,

    pub processed_at: String,

    pub raw_content: String,

    pub received_at: String,

    pub receiver_id: String,

    pub related_invoice_id: String,

    pub related_purchase_order_id: String,

    pub retry_count: i32,

    pub sender_id: String,

    pub status: String,

    pub updated_at: String,

    pub updated_by: String,

    pub validated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct EdiFormat {
    pub code: String,

    pub created_at: String,

    pub description: String,

    pub format_config: serde_json::Value,

    pub id: String,

    pub is_active: bool,

    pub name: String,

    pub supported_document_types: String,

    pub updated_at: String,

    pub version: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct EdiMapping {
    pub created_at: String,

    pub created_by: String,

    pub default_values: serde_json::Value,

    pub description: String,

    pub document_type: String,

    pub field_mappings: serde_json::Value,

    pub format_id: String,

    pub id: String,

    pub is_active: bool,

    pub mapping_name: String,

    pub transformation_rules: serde_json::Value,

    pub updated_at: String,

    pub updated_by: String,

    pub validation_rules: serde_json::Value,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetEdiDocumentResponse {
    pub acknowledgment_sent: bool,

    pub acknowledgment_sent_at: String,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub document_number: String,

    pub document_type: String,

    pub error_details: serde_json::Value,

    pub error_message: String,

    pub format_id: String,

    pub id: String,

    pub last_retry_at: String,

    pub metadata: serde_json::Value,

    pub parsed_at: String,

    pub parsed_data: serde_json::Value,

    pub processed_at: String,

    pub raw_content: String,

    pub received_at: String,

    pub receiver_id: String,

    pub related_invoice_id: String,

    pub related_purchase_order_id: String,

    pub retry_count: i32,

    pub sender_id: String,

    pub status: String,

    pub updated_at: String,

    pub updated_by: String,

    pub validated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetEdiMappingResponse {
    pub created_at: String,

    pub created_by: String,

    pub default_values: serde_json::Value,

    pub description: String,

    pub document_type: String,

    pub field_mappings: serde_json::Value,

    pub format_id: String,

    pub id: String,

    pub is_active: bool,

    pub mapping_name: String,

    pub transformation_rules: serde_json::Value,

    pub updated_at: String,

    pub updated_by: String,

    pub validation_rules: serde_json::Value,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ListEdiDocumentsResponse {
    pub items: Vec<EdiDocument>,

    pub limit: i32,

    pub page: i32,

    pub total: i32,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ListEdiMappingsResponse {
    pub items: Vec<EdiMapping>,

    pub limit: i32,

    pub page: i32,

    pub total: i32,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateEdiDocumentRequest {
    pub acknowledgment_sent: bool,

    pub error_message: String,

    pub parsed_data: serde_json::Value,

    pub related_invoice_id: String,

    pub related_purchase_order_id: String,

    pub status: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateEdiDocumentResponse {
    pub acknowledgment_sent: bool,

    pub acknowledgment_sent_at: String,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub document_number: String,

    pub document_type: String,

    pub error_details: serde_json::Value,

    pub error_message: String,

    pub format_id: String,

    pub id: String,

    pub last_retry_at: String,

    pub metadata: serde_json::Value,

    pub parsed_at: String,

    pub parsed_data: serde_json::Value,

    pub processed_at: String,

    pub raw_content: String,

    pub received_at: String,

    pub receiver_id: String,

    pub related_invoice_id: String,

    pub related_purchase_order_id: String,

    pub retry_count: i32,

    pub sender_id: String,

    pub status: String,

    pub updated_at: String,

    pub updated_by: String,

    pub validated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateEdiMappingRequest {
    pub default_values: serde_json::Value,

    pub description: String,

    pub field_mappings: serde_json::Value,

    pub is_active: bool,

    pub mapping_name: String,

    pub transformation_rules: serde_json::Value,

    pub validation_rules: serde_json::Value,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateEdiMappingResponse {
    pub created_at: String,

    pub created_by: String,

    pub default_values: serde_json::Value,

    pub description: String,

    pub document_type: String,

    pub field_mappings: serde_json::Value,

    pub format_id: String,

    pub id: String,

    pub is_active: bool,

    pub mapping_name: String,

    pub transformation_rules: serde_json::Value,

    pub updated_at: String,

    pub updated_by: String,

    pub validation_rules: serde_json::Value,
}
