// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct Budget {
    pub approval_status: String,

    pub approved_at: String,

    pub approved_by: String,

    pub budget_number: String,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub current_version_id: String,

    pub description: String,

    pub fiscal_year: i32,

    pub id: String,

    pub metadata: serde_json::Value,

    pub name: String,

    pub period_end: String,

    pub period_start: String,

    pub status: String,

    pub total_actual_amount: f64,

    pub total_budget_amount: f64,

    pub total_variance: f64,

    pub updated_at: String,

    pub updated_by: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct BudgetLine {
    pub account_id: String,

    pub actual_amount: f64,

    pub budget_amount: f64,

    pub budget_id: String,

    pub created_at: String,

    pub currency_code: String,

    pub id: String,

    pub notes: String,

    pub period_id: String,

    pub updated_at: String,

    pub variance: f64,

    pub variance_percent: f64,

    pub version_id: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct BudgetVariance {
    pub account_id: String,

    pub actual_amount: f64,

    pub budget_amount: f64,

    pub budget_id: String,

    pub created_at: String,

    pub currency_code: String,

    pub exceeds_threshold: bool,

    pub id: String,

    pub is_favorable: bool,

    pub last_calculated_at: String,

    pub period_id: String,

    pub updated_at: String,

    pub variance: f64,

    pub variance_percent: f64,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateBudgetLineRequest {
    pub account_id: String,

    pub budget_amount: f64,

    pub budget_id: String,

    pub currency_code: String,

    pub notes: String,

    pub period_id: String,

    pub version_id: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateBudgetLineResponse {
    pub account_id: String,

    pub actual_amount: f64,

    pub budget_amount: f64,

    pub budget_id: String,

    pub created_at: String,

    pub currency_code: String,

    pub id: String,

    pub notes: String,

    pub period_id: String,

    pub updated_at: String,

    pub variance: f64,

    pub variance_percent: f64,

    pub version_id: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateBudgetRequest {
    pub budget_number: String,

    pub company_id: String,

    pub currency_code: String,

    pub description: String,

    pub fiscal_year: i32,

    pub name: String,

    pub period_end: String,

    pub period_start: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateBudgetResponse {
    pub approval_status: String,

    pub approved_at: String,

    pub approved_by: String,

    pub budget_number: String,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub current_version_id: String,

    pub description: String,

    pub fiscal_year: i32,

    pub id: String,

    pub metadata: serde_json::Value,

    pub name: String,

    pub period_end: String,

    pub period_start: String,

    pub status: String,

    pub total_actual_amount: f64,

    pub total_budget_amount: f64,

    pub total_variance: f64,

    pub updated_at: String,

    pub updated_by: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateBudgetVarianceRequest {
    pub account_id: String,

    pub budget_id: String,

    pub currency_code: String,

    pub period_id: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateBudgetVarianceResponse {
    pub account_id: String,

    pub actual_amount: f64,

    pub budget_amount: f64,

    pub budget_id: String,

    pub created_at: String,

    pub currency_code: String,

    pub exceeds_threshold: bool,

    pub id: String,

    pub is_favorable: bool,

    pub last_calculated_at: String,

    pub period_id: String,

    pub updated_at: String,

    pub variance: f64,

    pub variance_percent: f64,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetBudgetLineResponse {
    pub account_id: String,

    pub actual_amount: f64,

    pub budget_amount: f64,

    pub budget_id: String,

    pub created_at: String,

    pub currency_code: String,

    pub id: String,

    pub notes: String,

    pub period_id: String,

    pub updated_at: String,

    pub variance: f64,

    pub variance_percent: f64,

    pub version_id: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetBudgetResponse {
    pub approval_status: String,

    pub approved_at: String,

    pub approved_by: String,

    pub budget_number: String,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub current_version_id: String,

    pub description: String,

    pub fiscal_year: i32,

    pub id: String,

    pub metadata: serde_json::Value,

    pub name: String,

    pub period_end: String,

    pub period_start: String,

    pub status: String,

    pub total_actual_amount: f64,

    pub total_budget_amount: f64,

    pub total_variance: f64,

    pub updated_at: String,

    pub updated_by: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetBudgetVarianceResponse {
    pub account_id: String,

    pub actual_amount: f64,

    pub budget_amount: f64,

    pub budget_id: String,

    pub created_at: String,

    pub currency_code: String,

    pub exceeds_threshold: bool,

    pub id: String,

    pub is_favorable: bool,

    pub last_calculated_at: String,

    pub period_id: String,

    pub updated_at: String,

    pub variance: f64,

    pub variance_percent: f64,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ListBudgetLinesResponse {
    pub items: Vec<BudgetLine>,

    pub limit: i32,

    pub page: i32,

    pub total: i32,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ListBudgetVariancesResponse {
    pub items: Vec<BudgetVariance>,

    pub limit: i32,

    pub page: i32,

    pub total: i32,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ListBudgetsResponse {
    pub items: Vec<Budget>,

    pub limit: i32,

    pub page: i32,

    pub total: i32,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateBudgetLineRequest {
    pub actual_amount: f64,

    pub budget_amount: f64,

    pub notes: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateBudgetLineResponse {
    pub account_id: String,

    pub actual_amount: f64,

    pub budget_amount: f64,

    pub budget_id: String,

    pub created_at: String,

    pub currency_code: String,

    pub id: String,

    pub notes: String,

    pub period_id: String,

    pub updated_at: String,

    pub variance: f64,

    pub variance_percent: f64,

    pub version_id: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateBudgetRequest {
    pub approval_status: String,

    pub description: String,

    pub name: String,

    pub status: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateBudgetResponse {
    pub approval_status: String,

    pub approved_at: String,

    pub approved_by: String,

    pub budget_number: String,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub current_version_id: String,

    pub description: String,

    pub fiscal_year: i32,

    pub id: String,

    pub metadata: serde_json::Value,

    pub name: String,

    pub period_end: String,

    pub period_start: String,

    pub status: String,

    pub total_actual_amount: f64,

    pub total_budget_amount: f64,

    pub total_variance: f64,

    pub updated_at: String,

    pub updated_by: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateBudgetVarianceRequest {
    pub actual_amount: f64,

    pub budget_amount: f64,

    pub exceeds_threshold: bool,

    pub is_favorable: bool,

    pub variance: f64,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateBudgetVarianceResponse {
    pub account_id: String,

    pub actual_amount: f64,

    pub budget_amount: f64,

    pub budget_id: String,

    pub created_at: String,

    pub currency_code: String,

    pub exceeds_threshold: bool,

    pub id: String,

    pub is_favorable: bool,

    pub last_calculated_at: String,

    pub period_id: String,

    pub updated_at: String,

    pub variance: f64,

    pub variance_percent: f64,
}
