// Generated crate for product/pricing
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/product/pricing/openapi.yaml

// Placeholder - will be replaced during code generation
