// Generated crate for helpdesk/knowledge-base
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/helpdesk/knowledge-base/openapi.yaml

// Placeholder - will be replaced during code generation
