// Generated crate for auth/idam
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/auth/idam/openapi.yaml

// Placeholder - will be replaced during code generation
