// Generated crate for infrastructure/gateway
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/infrastructure/gateway/openapi.yaml

// Placeholder - will be replaced during code generation
