//! Accounting suite foundation entities.
//!
//! This crate owns only shared Accounting invariants that must participate in one
//! transaction across service boundaries (legal entities, fiscal periods, posting,
//! idempotency, audit, and document-artifact linkage). Service-specific entities
//! live under `microservices/accounting/<service>/impl/src/models/`.
//!
//! ## Usage
//!
//! ```rust
//! use lifeguard::LifeEntityName;
//! use rerp_entities::accounting::foundation::account;
//!
//! // Access entity metadata
//! let entity = account::Entity::default();
//! println!("Table: {}", entity.table_name());
//! ```

pub mod accounting;

// Include the entity registry generated by build script
// Must be after module declarations so it can reference them
include!(concat!(env!("OUT_DIR"), "/entity_registry.rs"));

pub use accounting::foundation;
