// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file
use brrtrouter::dispatcher::HandlerRequest;
use brrtrouter::typed::TypedHandlerRequest;
use serde::{Deserialize, Serialize};
use std::convert::TryFrom;

#[derive(Debug, Deserialize, Serialize)]
pub struct Request {
    #[serde(rename = "id")]
    pub id: String,
}

#[derive(Debug, Serialize)]

pub struct Response {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "account_id")]
    pub account_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "created_at")]
    pub created_at: Option<String>,

    #[serde(rename = "currency_code")]
    pub currency_code: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "discount_amount")]
    pub discount_amount: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "discount_percent")]
    pub discount_percent: Option<f64>,

    #[serde(rename = "id")]
    pub id: String,

    #[serde(rename = "invoice_id")]
    pub invoice_id: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "line_number")]
    pub line_number: Option<i32>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "line_subtotal")]
    pub line_subtotal: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "line_total")]
    pub line_total: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "metadata")]
    pub metadata: Option<serde_json::Value>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "product_code")]
    pub product_code: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "product_description")]
    pub product_description: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "product_id")]
    pub product_id: Option<String>,

    #[serde(rename = "product_name")]
    pub product_name: String,

    #[serde(rename = "quantity")]
    pub quantity: f64,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "tax_amount")]
    pub tax_amount: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "tax_id")]
    pub tax_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "tax_rate")]
    pub tax_rate: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "unit_of_measure")]
    pub unit_of_measure: Option<String>,

    #[serde(rename = "unit_price")]
    pub unit_price: f64,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "updated_at")]
    pub updated_at: Option<String>,
}

impl TryFrom<HandlerRequest> for Request {
    type Error = anyhow::Error;

    fn try_from(req: HandlerRequest) -> Result<Self, Self::Error> {
        use serde_json::{Map, Value};

        let mut data_map = Map::new();

        if let Some(v) = req.get_path_param("id") {
            data_map.insert(
                "id".to_string(),
                brrtrouter::server::request::decode_param_value(
                    v,
                    Some(&serde_json::json!({"format":"uuid","type":"string"})),
                    None,
                    None,
                ),
            );
        } else {
            return Err(anyhow::anyhow!("Missing required parameter 'id'"));
        }

        if let Some(body) = req.body {
            match body {
                Value::Object(map) => {
                    for (k, v) in map {
                        data_map.insert(k, v);
                    }
                }
                other => {
                    data_map.insert("body".to_string(), other);
                }
            }
        }

        Ok(serde_json::from_value(Value::Object(data_map))?)
    }
}

#[allow(dead_code)]
pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    crate::controllers::get_invoice_line::handle(req)
}
