// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file
use brrtrouter::dispatcher::HandlerRequest;
use brrtrouter::typed::TypedHandlerRequest;
use serde::{Deserialize, Serialize};
use std::convert::TryFrom;

#[derive(Debug, Deserialize, Serialize)]
pub struct Request {
    #[serde(rename = "id")]
    pub id: String,
}

#[derive(Debug, Serialize)]

pub struct Response {
    #[serde(rename = "account_id")]
    pub account_id: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "actual_amount")]
    pub actual_amount: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "budget_amount")]
    pub budget_amount: Option<f64>,

    #[serde(rename = "budget_id")]
    pub budget_id: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "created_at")]
    pub created_at: Option<String>,

    #[serde(rename = "currency_code")]
    pub currency_code: String,

    #[serde(rename = "id")]
    pub id: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "notes")]
    pub notes: Option<String>,

    #[serde(rename = "period_id")]
    pub period_id: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "updated_at")]
    pub updated_at: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "variance")]
    pub variance: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "variance_percent")]
    pub variance_percent: Option<f64>,

    #[serde(rename = "version_id")]
    pub version_id: String,
}

impl TryFrom<HandlerRequest> for Request {
    type Error = anyhow::Error;

    fn try_from(req: HandlerRequest) -> Result<Self, Self::Error> {
        use serde_json::{Map, Value};

        let mut data_map = Map::new();

        if let Some(v) = req.get_path_param("id") {
            data_map.insert(
                "id".to_string(),
                brrtrouter::server::request::decode_param_value(
                    v,
                    Some(&serde_json::json!({"format":"uuid","type":"string"})),
                    None,
                    None,
                ),
            );
        } else {
            return Err(anyhow::anyhow!("Missing required parameter 'id'"));
        }

        if let Some(body) = req.body {
            match body {
                Value::Object(map) => {
                    for (k, v) in map {
                        data_map.insert(k, v);
                    }
                }
                other => {
                    data_map.insert("body".to_string(), other);
                }
            }
        }

        Ok(serde_json::from_value(Value::Object(data_map))?)
    }
}

#[allow(dead_code)]
pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    crate::controllers::get_budget_line::handle(req)
}
