// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file
use brrtrouter::dispatcher::HandlerRequest;
use brrtrouter::typed::TypedHandlerRequest;
use serde::{Deserialize, Serialize};
use std::convert::TryFrom;

#[derive(Debug, Deserialize, Serialize)]
pub struct Request {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "approval_status")]
    pub approval_status: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "description")]
    pub description: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "name")]
    pub name: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "status")]
    pub status: Option<String>,

    #[serde(rename = "id")]
    pub id: String,
}

#[derive(Debug, Serialize)]

pub struct Response {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "approval_status")]
    pub approval_status: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "approved_at")]
    pub approved_at: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "approved_by")]
    pub approved_by: Option<String>,

    #[serde(rename = "budget_number")]
    pub budget_number: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "company_id")]
    pub company_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "created_at")]
    pub created_at: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "created_by")]
    pub created_by: Option<String>,

    #[serde(rename = "currency_code")]
    pub currency_code: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "current_version_id")]
    pub current_version_id: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "description")]
    pub description: Option<String>,

    #[serde(rename = "fiscal_year")]
    pub fiscal_year: i32,

    #[serde(rename = "id")]
    pub id: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "metadata")]
    pub metadata: Option<serde_json::Value>,

    #[serde(rename = "name")]
    pub name: String,

    #[serde(rename = "period_end")]
    pub period_end: String,

    #[serde(rename = "period_start")]
    pub period_start: String,

    #[serde(rename = "status")]
    pub status: String,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "total_actual_amount")]
    pub total_actual_amount: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "total_budget_amount")]
    pub total_budget_amount: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "total_variance")]
    pub total_variance: Option<f64>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "updated_at")]
    pub updated_at: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "updated_by")]
    pub updated_by: Option<String>,
}

impl TryFrom<HandlerRequest> for Request {
    type Error = anyhow::Error;

    fn try_from(req: HandlerRequest) -> Result<Self, Self::Error> {
        use serde_json::{Map, Value};

        let mut data_map = Map::new();

        if let Some(v) = req.get_path_param("id") {
            data_map.insert(
                "id".to_string(),
                brrtrouter::server::request::decode_param_value(
                    v,
                    Some(&serde_json::json!({"format":"uuid","type":"string"})),
                    None,
                    None,
                ),
            );
        } else {
            return Err(anyhow::anyhow!("Missing required parameter 'id'"));
        }

        if let Some(body) = req.body {
            match body {
                Value::Object(map) => {
                    for (k, v) in map {
                        data_map.insert(k, v);
                    }
                }
                other => {
                    data_map.insert("body".to_string(), other);
                }
            }
        }

        Ok(serde_json::from_value(Value::Object(data_map))?)
    }
}

#[allow(dead_code)]
pub fn handler(req: TypedHandlerRequest<Request>) -> Response {
    crate::controllers::update_budget::handle(req)
}
