apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rerp

resources:
  - general-ledger.yaml
  - invoice.yaml

configMapGenerator:
  - name: rerp-accounting-common-helm-values
    files:
      - values.yaml=values/common.yaml

generatorOptions:
  disableNameSuffixHash: true
  immutable: false
