// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateInvoiceLineRequest {
    pub account_id: String,

    pub discount_amount: f64,

    pub discount_percent: f64,

    pub invoice_id: String,

    pub line_number: i32,

    pub product_code: String,

    pub product_description: String,

    pub product_id: String,

    pub product_name: String,

    pub quantity: f64,

    pub tax_id: String,

    pub tax_rate: f64,

    pub unit_of_measure: String,

    pub unit_price: f64,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateInvoiceLineResponse {
    pub account_id: String,

    pub created_at: String,

    pub currency_code: String,

    pub discount_amount: f64,

    pub discount_percent: f64,

    pub id: String,

    pub invoice_id: String,

    pub line_number: i32,

    pub line_subtotal: f64,

    pub line_total: f64,

    pub metadata: serde_json::Value,

    pub product_code: String,

    pub product_description: String,

    pub product_id: String,

    pub product_name: String,

    pub quantity: f64,

    pub tax_amount: f64,

    pub tax_id: String,

    pub tax_rate: f64,

    pub unit_of_measure: String,

    pub unit_price: f64,

    pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateInvoiceRequest {
    pub company_id: String,

    pub currency_code: String,

    pub customer_id: String,

    pub due_date: String,

    pub exchange_rate: f64,

    pub internal_notes: String,

    pub invoice_date: String,

    pub invoice_number: String,

    pub invoice_type: String,

    pub notes: String,

    pub payment_term_id: String,

    pub reference_number: String,

    pub vendor_id: String,

    pub vendor_reference: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateInvoiceResponse {
    pub cancelled_at: String,

    pub company_id: String,

    pub created_at: String,

    pub currency_code: String,

    pub customer_id: String,

    pub discount_amount: f64,

    pub due_date: String,

    pub exchange_rate: f64,

    pub id: String,

    pub internal_notes: String,

    pub invoice_date: String,

    pub invoice_number: String,

    pub invoice_type: String,

    pub metadata: serde_json::Value,

    pub notes: String,

    pub outstanding_amount: f64,

    pub paid_amount: f64,

    pub paid_at: String,

    pub payment_state: String,

    pub payment_term_id: String,

    pub posted_at: String,

    pub reference_number: String,

    pub status: String,

    pub subtotal: f64,

    pub tax_amount: f64,

    pub total_amount: f64,

    pub updated_at: String,

    pub vendor_id: String,

    pub vendor_reference: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetInvoiceLineResponse {
    pub account_id: String,

    pub created_at: String,

    pub currency_code: String,

    pub discount_amount: f64,

    pub discount_percent: f64,

    pub id: String,

    pub invoice_id: String,

    pub line_number: i32,

    pub line_subtotal: f64,

    pub line_total: f64,

    pub metadata: serde_json::Value,

    pub product_code: String,

    pub product_description: String,

    pub product_id: String,

    pub product_name: String,

    pub quantity: f64,

    pub tax_amount: f64,

    pub tax_id: String,

    pub tax_rate: f64,

    pub unit_of_measure: String,

    pub unit_price: f64,

    pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetInvoiceResponse {
    pub cancelled_at: String,

    pub company_id: String,

    pub created_at: String,

    pub currency_code: String,

    pub customer_id: String,

    pub discount_amount: f64,

    pub due_date: String,

    pub exchange_rate: f64,

    pub id: String,

    pub internal_notes: String,

    pub invoice_date: String,

    pub invoice_number: String,

    pub invoice_type: String,

    pub metadata: serde_json::Value,

    pub notes: String,

    pub outstanding_amount: f64,

    pub paid_amount: f64,

    pub paid_at: String,

    pub payment_state: String,

    pub payment_term_id: String,

    pub posted_at: String,

    pub reference_number: String,

    pub status: String,

    pub subtotal: f64,

    pub tax_amount: f64,

    pub total_amount: f64,

    pub updated_at: String,

    pub vendor_id: String,

    pub vendor_reference: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct Invoice {
    pub cancelled_at: String,

    pub company_id: String,

    pub created_at: String,

    pub currency_code: String,

    pub customer_id: String,

    pub discount_amount: f64,

    pub due_date: String,

    pub exchange_rate: f64,

    pub id: String,

    pub internal_notes: String,

    pub invoice_date: String,

    pub invoice_number: String,

    pub invoice_type: String,

    pub metadata: serde_json::Value,

    pub notes: String,

    pub outstanding_amount: f64,

    pub paid_amount: f64,

    pub paid_at: String,

    pub payment_state: String,

    pub payment_term_id: String,

    pub posted_at: String,

    pub reference_number: String,

    pub status: String,

    pub subtotal: f64,

    pub tax_amount: f64,

    pub total_amount: f64,

    pub updated_at: String,

    pub vendor_id: String,

    pub vendor_reference: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct InvoiceLine {
    pub account_id: String,

    pub created_at: String,

    pub currency_code: String,

    pub discount_amount: f64,

    pub discount_percent: f64,

    pub id: String,

    pub invoice_id: String,

    pub line_number: i32,

    pub line_subtotal: f64,

    pub line_total: f64,

    pub metadata: serde_json::Value,

    pub product_code: String,

    pub product_description: String,

    pub product_id: String,

    pub product_name: String,

    pub quantity: f64,

    pub tax_amount: f64,

    pub tax_id: String,

    pub tax_rate: f64,

    pub unit_of_measure: String,

    pub unit_price: f64,

    pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ListInvoiceLinesResponse {
    pub items: Vec<InvoiceLine>,

    pub limit: i32,

    pub page: i32,

    pub total: i32,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ListInvoicesResponse {
    pub items: Vec<Invoice>,

    pub limit: i32,

    pub page: i32,

    pub total: i32,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateInvoiceLineRequest {
    pub discount_amount: f64,

    pub discount_percent: f64,

    pub product_name: String,

    pub quantity: f64,

    pub tax_id: String,

    pub tax_rate: f64,

    pub unit_price: f64,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateInvoiceLineResponse {
    pub account_id: String,

    pub created_at: String,

    pub currency_code: String,

    pub discount_amount: f64,

    pub discount_percent: f64,

    pub id: String,

    pub invoice_id: String,

    pub line_number: i32,

    pub line_subtotal: f64,

    pub line_total: f64,

    pub metadata: serde_json::Value,

    pub product_code: String,

    pub product_description: String,

    pub product_id: String,

    pub product_name: String,

    pub quantity: f64,

    pub tax_amount: f64,

    pub tax_id: String,

    pub tax_rate: f64,

    pub unit_of_measure: String,

    pub unit_price: f64,

    pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateInvoiceRequest {
    pub due_date: String,

    pub internal_notes: String,

    pub invoice_date: String,

    pub metadata: serde_json::Value,

    pub notes: String,

    pub payment_state: String,

    pub status: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateInvoiceResponse {
    pub cancelled_at: String,

    pub company_id: String,

    pub created_at: String,

    pub currency_code: String,

    pub customer_id: String,

    pub discount_amount: f64,

    pub due_date: String,

    pub exchange_rate: f64,

    pub id: String,

    pub internal_notes: String,

    pub invoice_date: String,

    pub invoice_number: String,

    pub invoice_type: String,

    pub metadata: serde_json::Value,

    pub notes: String,

    pub outstanding_amount: f64,

    pub paid_amount: f64,

    pub paid_at: String,

    pub payment_state: String,

    pub payment_term_id: String,

    pub posted_at: String,

    pub reference_number: String,

    pub status: String,

    pub subtotal: f64,

    pub tax_amount: f64,

    pub total_amount: f64,

    pub updated_at: String,

    pub vendor_id: String,

    pub vendor_reference: String,
}
