// Generated crate for field-service/core
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/field-service/core/openapi.yaml

// Placeholder - will be replaced during code generation
