// Generated crate for website/builder
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/website/builder/openapi.yaml

// Placeholder - will be replaced during code generation
