// Generated crate for hr/skills
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/hr/skills/openapi.yaml

// Placeholder - will be replaced during code generation
