// Generated crate for manufacturing/subcontracting
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/manufacturing/subcontracting/openapi.yaml

// Placeholder - will be replaced during code generation
