// Generated crate for accounting/asset
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/accounting/asset/openapi.yaml

// Placeholder - will be replaced during code generation
