// Generated crate for marketing/social-media
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/marketing/social-media/openapi.yaml

// Placeholder - will be replaced during code generation
