// Auto-generated mod.rs for general-ledger entities
// DO NOT EDIT - this is generated by the build system

pub mod account;
pub mod account_balance;
pub mod chart_of_accounts;
pub mod journal_entry;
pub mod journal_entry_line;

pub mod entity_registry {
    include!(concat!(env!("OUT_DIR"), "/entity_registry.rs"));
}
