// Generated crate for automation/core
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/automation/core/openapi.yaml

// Placeholder - will be replaced during code generation
