//! Accounting Domain Entities
//!
//! This library provides Lifeguard entity definitions for an accounting system,
//! organized by service domain (General Ledger, Invoice, Accounts Receivable, Accounts Payable).
//!
//! ## Usage
//!
//! ```rust
//! use rerp_entities::accounting::general_ledger::ChartOfAccount;
//! use lifeguard::LifeModelTrait;
//!
//! // Access entity metadata
//! let entity = ChartOfAccount::Entity::default();
//! println!("Table: {}", entity.table_name());
//! ```
//!
//! ## Entity Organization
//!
//! Entities are organized by service domain:
//! - `accounting::general_ledger` - Core accounting entities
//! - `accounting::invoice` - Invoice management
//! - `accounting::accounts_receivable` - AR management
//! - `accounting::accounts_payable` - AP management

pub mod accounting;

// Include the entity registry generated by build script
// Must be after module declarations so it can reference them
include!(concat!(env!("OUT_DIR"), "/entity_registry.rs"));

// Re-export for convenience
pub use accounting::*;
