// Generated crate for documents/core
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/documents/core/openapi.yaml

// Placeholder - will be replaced during code generation
