// Generated crate for crm/livechat
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/crm/livechat/openapi.yaml

// Placeholder - will be replaced during code generation
