// Generated crate for accounting/budget
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/accounting/budget/openapi.yaml

// Placeholder - will be replaced during code generation
