// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file
use brrtrouter::dispatcher::Dispatcher;
use brrtrouter::spec::RouteMeta;
use brrtrouter::typed::spawn_typed_with_stack_size_and_name;
// Note: avoid wildcard imports to reduce warnings

/// # Safety
/// This function spawns handler coroutines. Callers must ensure coroutine runtime is set up.
#[allow(dead_code)]
pub unsafe fn register_all(dispatcher: &mut Dispatcher) {
    dispatcher.register_typed_with_stack_size(
        "list_asset_registers",
        crate::controllers::list_asset_registers::ListAssetRegistersController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "create_asset_register",
        crate::controllers::create_asset_register::CreateAssetRegisterController,
        16384,
    );
    dispatcher.register_typed_with_stack_size(
        "get_asset_register",
        crate::controllers::get_asset_register::GetAssetRegisterController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "update_asset_register",
        crate::controllers::update_asset_register::UpdateAssetRegisterController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "delete_asset_register",
        crate::controllers::delete_asset_register::DeleteAssetRegisterController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "list_assets",
        crate::controllers::list_assets::ListAssetsController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "create_asset",
        crate::controllers::create_asset::CreateAssetController,
        16384,
    );
    dispatcher.register_typed_with_stack_size(
        "get_asset",
        crate::controllers::get_asset::GetAssetController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "update_asset",
        crate::controllers::update_asset::UpdateAssetController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "delete_asset",
        crate::controllers::delete_asset::DeleteAssetController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "list_depreciations",
        crate::controllers::list_depreciations::ListDepreciationsController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "create_depreciation",
        crate::controllers::create_depreciation::CreateDepreciationController,
        16384,
    );
    dispatcher.register_typed_with_stack_size(
        "get_depreciation",
        crate::controllers::get_depreciation::GetDepreciationController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "update_depreciation",
        crate::controllers::update_depreciation::UpdateDepreciationController,
        20480,
    );
    dispatcher.register_typed_with_stack_size(
        "delete_depreciation",
        crate::controllers::delete_depreciation::DeleteDepreciationController,
        20480,
    );
}

/// Dynamically register handlers for the provided routes using their handler names.
/// # Safety
/// This function spawns handler coroutines. Callers must ensure coroutine runtime is set up.
///
/// **IMPORTANT**: This function will clear ALL existing handlers before registering new ones
/// to prevent memory leaks from accumulating coroutines.
pub unsafe fn register_from_spec(dispatcher: &mut Dispatcher, routes: &[RouteMeta]) {
    // Clear all existing handlers to prevent memory leaks
    // The old senders will be dropped, causing their coroutines to exit
    dispatcher.handlers.clear();

    // Also clear worker pools to prevent resource leaks from previous pool-based registrations
    dispatcher.worker_pools.clear();

    for route in routes {
        // JSF P0-2: Use as_ref() for Arc<str> -> &str conversion
        match route.handler_name.as_ref() {
            "list_asset_registers" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::list_asset_registers::ListAssetRegistersController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "create_asset_register" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::create_asset_register::CreateAssetRegisterController,
                    16384,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "get_asset_register" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::get_asset_register::GetAssetRegisterController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "update_asset_register" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::update_asset_register::UpdateAssetRegisterController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "delete_asset_register" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::delete_asset_register::DeleteAssetRegisterController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "list_assets" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::list_assets::ListAssetsController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "create_asset" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::create_asset::CreateAssetController,
                    16384,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "get_asset" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::get_asset::GetAssetController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "update_asset" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::update_asset::UpdateAssetController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "delete_asset" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::delete_asset::DeleteAssetController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "list_depreciations" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::list_depreciations::ListDepreciationsController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "create_depreciation" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::create_depreciation::CreateDepreciationController,
                    16384,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "get_depreciation" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::get_depreciation::GetDepreciationController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "update_depreciation" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::update_depreciation::UpdateDepreciationController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }
            "delete_depreciation" => {
                let tx = spawn_typed_with_stack_size_and_name(
                    crate::controllers::delete_depreciation::DeleteDepreciationController,
                    20480,
                    Some(route.handler_name.as_ref()),
                );
                dispatcher.add_route(route.clone(), tx);
            }

            _ => {}
        }
    }
}
