// Generated crate for analytics/dashboards
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/analytics/dashboards/openapi.yaml

// Placeholder - will be replaced during code generation
