// Auto-generated mod.rs for asset entities
// DO NOT EDIT - this is generated by the build system

pub mod asset;
pub mod asset_category;
pub mod asset_depreciation;
pub mod asset_transaction;

pub mod entity_registry {
    include!(concat!(env!("OUT_DIR"), "/entity_registry.rs"));
}
