// Auto-generated mod.rs for financial-reports entities
// DO NOT EDIT - this is generated by the build system

pub mod financial_report;
pub mod report_data;
pub mod report_schedule;
pub mod report_template;

pub mod entity_registry {
    include!(concat!(env!("OUT_DIR"), "/entity_registry.rs"));
}
