// Generated crate for auth/rbac
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/auth/rbac/openapi.yaml

// Placeholder - will be replaced during code generation
