// Generated crate for sales/subscription
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/sales/subscription/openapi.yaml

// Placeholder - will be replaced during code generation
