// Generated crate for pos/core
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/pos/core/openapi.yaml

// Placeholder - will be replaced during code generation
