// Generated crate for hr/appraisal
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/hr/appraisal/openapi.yaml

// Placeholder - will be replaced during code generation
