// Auto-generated mod.rs for documents-render entities
// DO NOT EDIT - this is generated by the build system

// Entity modules would go here (discovered by build.rs)

pub mod entity_registry {
    include!(concat!(env!("OUT_DIR"), "/entity_registry.rs"));
}
