// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation

pub mod create_document_rendition;
pub mod create_document_rendition_copy;
pub mod create_document_rendition_download;
pub mod create_document_template;
pub mod create_document_template_version;
pub mod get_document_rendition;
pub mod get_document_template;
pub mod get_document_template_version;
pub mod list_document_template_versions;
pub mod list_document_templates;
pub mod list_source_document_renditions;
pub mod preview_document_template_version;
pub mod publish_document_template_version;
pub mod retire_document_template_version;
pub mod validate_document_template_version;
