// Generated crate for hr/payroll
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/hr/payroll/openapi.yaml

// Placeholder - will be replaced during code generation
