// Generated crate for accounting/financial-reports
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/accounting/financial-reports/openapi.yaml

// Placeholder - will be replaced during code generation
