service:
  name: accounts-payable
image:
  repository: localhost:5001
  name: rerp-accounting-accounts-payable
  tag: tilt
  pullPolicy: IfNotPresent
deployment:
  replicas: 1
  namespace: rerp
app:
  binaryName: accounts_payable
  serviceName: accounts-payable
