service:
  name: bff
image:
  repository: localhost:5001
  name: rerp-accounting-bff
  tag: tilt
  pullPolicy: IfNotPresent
deployment:
  replicas: 1
  namespace: rerp
app:
  binaryName: bff
  serviceName: bff
