service:
  name: billing
image:
  repository: localhost:5001
  name: rerp-billing
  tag: tilt
  pullPolicy: IfNotPresent
deployment:
  replicas: 1
  namespace: rerp
app:
  binaryName: billing_service_api
  serviceName: billing
