// Generated crate for esg/core
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/esg/core/openapi.yaml

// Placeholder - will be replaced during code generation
