// Generated crate for manufacturing/core
// This file will be auto-generated by BRRTRouter from OpenAPI spec
// OpenAPI spec: ../../openapi/manufacturing/core/openapi.yaml

// Placeholder - will be replaced during code generation
