// ⚠️ WARNING: This file is auto-generated by BRRTRouter
// ⚠️ DO NOT MODIFY - Changes will be overwritten on next generation
// ⚠️ To modify API behavior, edit the OpenAPI spec and regenerate
// ⚠️ To implement business logic, edit the corresponding controller file
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct BankAccount {
    pub account_name: String,

    pub account_number: String,

    pub account_type: String,

    pub bank_code: String,

    pub bank_name: String,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub current_balance: f64,

    pub id: String,

    pub is_active: bool,

    pub last_reconciled_at: String,

    pub last_synced_at: String,

    pub metadata: serde_json::Value,

    pub reconciled_balance: f64,

    pub sync_credentials: String,

    pub sync_provider: String,

    pub updated_at: String,

    pub updated_by: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct BankStatement {
    pub bank_account_id: String,

    pub closing_balance: f64,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub id: String,

    pub import_format: String,

    pub import_source: String,

    pub imported_at: String,

    pub imported_by: String,

    pub metadata: serde_json::Value,

    pub opening_balance: f64,

    pub period_end: String,

    pub period_start: String,

    pub reconciled_at: String,

    pub reconciled_by: String,

    pub statement_date: String,

    pub statement_number: String,

    pub status: String,

    pub total_credits: f64,

    pub total_debits: f64,

    pub transaction_count: i32,

    pub updated_at: String,

    pub updated_by: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct BankTransaction {
    pub amount: f64,

    pub balance_after: f64,

    pub bank_account_id: String,

    pub created_at: String,

    pub currency_code: String,

    pub description: String,

    pub id: String,

    pub matched_at: String,

    pub matched_payment_id: String,

    pub metadata: serde_json::Value,

    pub reconciled_statement_id: String,

    pub reference: String,

    pub statement_id: String,

    pub statement_line_number: i32,

    pub status: String,

    pub transaction_date: String,

    pub transaction_type: String,

    pub updated_at: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateBankAccountRequest {
    pub account_name: String,

    pub account_number: String,

    pub account_type: String,

    pub bank_code: String,

    pub bank_name: String,

    pub company_id: String,

    pub currency_code: String,

    pub is_active: bool,

    pub sync_provider: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateBankAccountResponse {
    pub account_name: String,

    pub account_number: String,

    pub account_type: String,

    pub bank_code: String,

    pub bank_name: String,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub current_balance: f64,

    pub id: String,

    pub is_active: bool,

    pub last_reconciled_at: String,

    pub last_synced_at: String,

    pub metadata: serde_json::Value,

    pub reconciled_balance: f64,

    pub sync_credentials: String,

    pub sync_provider: String,

    pub updated_at: String,

    pub updated_by: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateBankStatementRequest {
    pub bank_account_id: String,

    pub closing_balance: f64,

    pub company_id: String,

    pub currency_code: String,

    pub import_format: String,

    pub import_source: String,

    pub opening_balance: f64,

    pub period_end: String,

    pub period_start: String,

    pub statement_date: String,

    pub statement_number: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateBankStatementResponse {
    pub bank_account_id: String,

    pub closing_balance: f64,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub id: String,

    pub import_format: String,

    pub import_source: String,

    pub imported_at: String,

    pub imported_by: String,

    pub metadata: serde_json::Value,

    pub opening_balance: f64,

    pub period_end: String,

    pub period_start: String,

    pub reconciled_at: String,

    pub reconciled_by: String,

    pub statement_date: String,

    pub statement_number: String,

    pub status: String,

    pub total_credits: f64,

    pub total_debits: f64,

    pub transaction_count: i32,

    pub updated_at: String,

    pub updated_by: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateBankTransactionRequest {
    pub amount: f64,

    pub bank_account_id: String,

    pub currency_code: String,

    pub description: String,

    pub reference: String,

    pub statement_id: String,

    pub transaction_date: String,

    pub transaction_type: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateReconciliationRequest {
    pub bank_account_id: String,

    pub company_id: String,

    pub currency_code: String,

    pub notes: String,

    pub reconciliation_date: String,

    pub statement_id: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct CreateReconciliationResponse {
    pub bank_account_id: String,

    pub bank_balance: f64,

    pub book_balance: f64,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub difference: f64,

    pub id: String,

    pub metadata: serde_json::Value,

    pub notes: String,

    pub outstanding_deposits_amount: f64,

    pub outstanding_deposits_count: i32,

    pub outstanding_withdrawals_amount: f64,

    pub outstanding_withdrawals_count: i32,

    pub reconciled_at: String,

    pub reconciled_by: String,

    pub reconciliation_date: String,

    pub statement_id: String,

    pub status: String,

    pub updated_at: String,

    pub updated_by: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetBankAccountResponse {
    pub account_name: String,

    pub account_number: String,

    pub account_type: String,

    pub bank_code: String,

    pub bank_name: String,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub current_balance: f64,

    pub id: String,

    pub is_active: bool,

    pub last_reconciled_at: String,

    pub last_synced_at: String,

    pub metadata: serde_json::Value,

    pub reconciled_balance: f64,

    pub sync_credentials: String,

    pub sync_provider: String,

    pub updated_at: String,

    pub updated_by: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetBankStatementResponse {
    pub bank_account_id: String,

    pub closing_balance: f64,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub id: String,

    pub import_format: String,

    pub import_source: String,

    pub imported_at: String,

    pub imported_by: String,

    pub metadata: serde_json::Value,

    pub opening_balance: f64,

    pub period_end: String,

    pub period_start: String,

    pub reconciled_at: String,

    pub reconciled_by: String,

    pub statement_date: String,

    pub statement_number: String,

    pub status: String,

    pub total_credits: f64,

    pub total_debits: f64,

    pub transaction_count: i32,

    pub updated_at: String,

    pub updated_by: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GetReconciliationResponse {
    pub bank_account_id: String,

    pub bank_balance: f64,

    pub book_balance: f64,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub difference: f64,

    pub id: String,

    pub metadata: serde_json::Value,

    pub notes: String,

    pub outstanding_deposits_amount: f64,

    pub outstanding_deposits_count: i32,

    pub outstanding_withdrawals_amount: f64,

    pub outstanding_withdrawals_count: i32,

    pub reconciled_at: String,

    pub reconciled_by: String,

    pub reconciliation_date: String,

    pub statement_id: String,

    pub status: String,

    pub updated_at: String,

    pub updated_by: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ListBankAccountsResponse {
    pub items: Vec<BankAccount>,

    pub limit: i32,

    pub page: i32,

    pub total: i32,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ListBankStatementsResponse {
    pub items: Vec<BankStatement>,

    pub limit: i32,

    pub page: i32,

    pub total: i32,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct ListReconciliationsResponse {
    pub items: Vec<Reconciliation>,

    pub limit: i32,

    pub page: i32,

    pub total: i32,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct Reconciliation {
    pub bank_account_id: String,

    pub bank_balance: f64,

    pub book_balance: f64,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub difference: f64,

    pub id: String,

    pub metadata: serde_json::Value,

    pub notes: String,

    pub outstanding_deposits_amount: f64,

    pub outstanding_deposits_count: i32,

    pub outstanding_withdrawals_amount: f64,

    pub outstanding_withdrawals_count: i32,

    pub reconciled_at: String,

    pub reconciled_by: String,

    pub reconciliation_date: String,

    pub statement_id: String,

    pub status: String,

    pub updated_at: String,

    pub updated_by: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateBankAccountRequest {
    pub account_name: String,

    pub account_type: String,

    pub bank_code: String,

    pub bank_name: String,

    pub is_active: bool,

    pub sync_provider: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateBankAccountResponse {
    pub account_name: String,

    pub account_number: String,

    pub account_type: String,

    pub bank_code: String,

    pub bank_name: String,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub current_balance: f64,

    pub id: String,

    pub is_active: bool,

    pub last_reconciled_at: String,

    pub last_synced_at: String,

    pub metadata: serde_json::Value,

    pub reconciled_balance: f64,

    pub sync_credentials: String,

    pub sync_provider: String,

    pub updated_at: String,

    pub updated_by: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateBankStatementRequest {
    pub reconciled_at: String,

    pub reconciled_by: String,

    pub status: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateBankStatementResponse {
    pub bank_account_id: String,

    pub closing_balance: f64,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub id: String,

    pub import_format: String,

    pub import_source: String,

    pub imported_at: String,

    pub imported_by: String,

    pub metadata: serde_json::Value,

    pub opening_balance: f64,

    pub period_end: String,

    pub period_start: String,

    pub reconciled_at: String,

    pub reconciled_by: String,

    pub statement_date: String,

    pub statement_number: String,

    pub status: String,

    pub total_credits: f64,

    pub total_debits: f64,

    pub transaction_count: i32,

    pub updated_at: String,

    pub updated_by: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateBankTransactionRequest {
    pub description: String,

    pub matched_payment_id: String,

    pub status: String,

    pub transaction_type: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateReconciliationRequest {
    pub bank_balance: f64,

    pub book_balance: f64,

    pub notes: String,

    pub status: String,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct UpdateReconciliationResponse {
    pub bank_account_id: String,

    pub bank_balance: f64,

    pub book_balance: f64,

    pub company_id: String,

    pub created_at: String,

    pub created_by: String,

    pub currency_code: String,

    pub difference: f64,

    pub id: String,

    pub metadata: serde_json::Value,

    pub notes: String,

    pub outstanding_deposits_amount: f64,

    pub outstanding_deposits_count: i32,

    pub outstanding_withdrawals_amount: f64,

    pub outstanding_withdrawals_count: i32,

    pub reconciled_at: String,

    pub reconciled_by: String,

    pub reconciliation_date: String,

    pub statement_id: String,

    pub status: String,

    pub updated_at: String,

    pub updated_by: String,
}
